# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=30

plugins=(git)

source $ZSH/oh-my-zsh.sh


eval `dircolors ~/.dir_colors/dircolors`

#################
# Env variables
#################

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

export MY_SCRIPTS=../scripts
export MIGRATE_DB_SCRIPT=$MY_SCRIPTS/migrate_db.sh
export FIRST_COMMIT_SCRIPT=$MY_SCRIPTS/first_commit.sh
export GET_PID_ON_PORT_SCRIPT=$MY_SCRIPTS/get_pid_on_port.sh


#################
# Aliases
#################

alias dev="cd $HOME/dev"
alias self="cd $HOME/code"

alias dcd="docker-compose down"
alias dcu="docker-compose up"
alias dcdu="dcd && dcu"

alias ys="yarn start"
alias yi="yarn install"
alias yis="yi && ys"

# scala
alias hc="curl http://localhost:9000/healthcheck"
alias sr="sbt run"

alias g8scala="sbt new scala/scala-seed.g8"
alias g8scala3="sbt new scala/scala3.g8"
alias g8play="sbt new playframework/play-scala-seed.g8"

alias gg="git gui"

# self
alias blog="self && blog"
alias bejs="bundle exec jekyll serve"

alias bookmarks="self && bookmarks"

alias localkafka="dev && scripts && ./start-local-kafka.sh"
alias migratedb=migrateDbScript
alias firstcommit=firstCommitScript
alias startcomponent=startComponentScript

alias getPidOnPort=getPidOnPortScript

## TODO maybe migrate those functions to another file
firstCommitScript() {
    bash $FIRST_COMMIT_SCRIPT $1
}

startComponentScript() {
    if [ -n "$1" ]
    then
        python3 $START_COMPONENT_SCRIPT $1
    fi   
}

getPidOnPortScript() {
    if [ -n "$1" ]
    then
        bash $GET_PID_ON_PORT_SCRIPT $1
    fi
}